# Generated by Django 4.2.4 on 2023-08-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/default/default_avatar.png', upload_to='images/user/', verbose_name='Image'),
        ),
    ]
